[versions]
agp = "7.2.1"
androidX-lifecycle = "2.4.1"
androidX-room = "2.4.2"
appCenter = "4.4.3"
grpc = "1.47.0"
hiddenApiRefine = "3.1.1"
kotlin = "1.6.21"
protoc = "3.21.1"
protoc-javalite = "3.21.1"
square-moshi = "1.13.0"
square-retrofit = "2.9.0"
zhaobozhen = "1.1.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
hiddenApiRefine = { id = "dev.rikka.tools.refine", version.ref = "hiddenApiRefine" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.10.0" }
ksp = { id = "com.google.devtools.ksp", version = "1.6.21-1.0.5" }
protobuf = { id = "com.google.protobuf", version = "0.8.18" }

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinX-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.2"
agp-desugering = "com.android.tools:desugar_jdk_libs:1.1.5"

androidX-activity = "androidx.activity:activity-ktx:1.4.0"
androidX-annotation = "androidx.annotation:annotation:1.3.0"
androidX-appCompat = "androidx.appcompat:appcompat:1.6.0-alpha04"
androidX-browser = "androidx.browser:browser:1.4.0"
androidX-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidX-core = "androidx.core:core-ktx:1.9.0-alpha04"
androidX-fragment = "androidx.fragment:fragment-ktx:1.4.1"
androidX-lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidX-lifecycle" }
androidX-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidX-lifecycle" }
androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidX-lifecycle" }
androidX-preference = "androidx.preference:preference-ktx:1.2.0"
androidX-recyclerView = "androidx.recyclerview:recyclerview:1.2.1"
androidX-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidX-room" }
androidX-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidX-room" }
androidX-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidX-room" }
androidX-viewPager2 = "androidx.viewpager2:viewpager2:1.1.0-alpha01"
androidX-window = "androidx.window:window:1.0.0"

square-leakCanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
square-moshi = { module = "com.squareup.moshi:moshi", version.ref = "square-moshi" }
square-moshi-compiler = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "square-moshi" }
square-okHttp = "com.squareup.okhttp3:okhttp:4.9.3"
square-okio = "com.squareup.okio:okio:3.1.0"
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit" }
square-retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "square-retrofit" }

google-material = "com.google.android.material:material:1.6.1"
google-protobuf-javaLite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protoc-javalite" }
google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }

grpc-gen = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }

rikka-refine-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "hiddenApiRefine" }
rikka-refine-compiler = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "hiddenApiRefine" }
rikka-refine-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "hiddenApiRefine" }
rikkax-appcompat = "dev.rikka.rikkax.appcompat:appcompat:1.4.1"
rikkax-borderview = "dev.rikka.rikkax.widget:borderview:1.1.0"
rikkax-core = "dev.rikka.rikkax.core:core:1.4.0"
rikkax-insets = "dev.rikka.rikkax.insets:insets:1.2.0"
rikkax-layoutinflater = "dev.rikka.rikkax.layoutinflater:layoutinflater:1.2.0"
rikkax-material = "dev.rikka.rikkax.material:material:1.6.6"
rikkax-recyclerview = "dev.rikka.rikkax.recyclerview:recyclerview-ktx:1.3.1"
rikkax-simplemenu-preference = "dev.rikka.rikkax.preference:simplemenu-preference:1.0.3"

appCenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appCenter" }
appCenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appCenter" }
appIconLoader = "me.zhanghai.android.appiconloader:appiconloader:1.4.0"
brvah = "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.7"
cascade = "me.saket.cascade:cascade:1.3.0"
coil = "io.coil-kt:coil:2.1.0"
dexLib2 = "org.smali:dexlib2:2.5.2"
drakeet-about = "com.drakeet.about:about:2.5.1"
drakeet-multitype = "com.drakeet.multitype:multitype:4.3.0"
fastScroll = "me.zhanghai.android.fastscroll:library:1.1.8"
hiddenApiBypass = "org.lsposed.hiddenapibypass:hiddenapibypass:4.3"
javax-annotation = "javax.annotation:javax.annotation-api:1.3.2"
lottie = "com.airbnb.android:lottie:5.2.0"
mpAndroidChart = "com.github.PhilJay:MPAndroidChart:3.1.0"
once = "com.jonathanfinerty.once:once:1.3.1"
processPhoenix = "com.jakewharton:process-phoenix:2.1.2"
timber = "com.jakewharton.timber:timber:5.0.1"
zhaobozhen-axml = { module = "com.github.zhaobozhen.libraries:axml", version.ref = "zhaobozhen" }
zhaobozhen-me = { module = "com.github.zhaobozhen.libraries:me", version.ref = "zhaobozhen" }
zhaobozhen-utils = { module = "com.github.zhaobozhen.libraries:utils", version.ref = "zhaobozhen" }
lc-rules = "com.github.zhaobozhen:LibChecker-Rules-Bundle:24.2"
slf4j = "org.slf4j:slf4j-simple:1.7.36"

[bundles]
androidX-lifecycle = [
  "androidX-lifecycle-viewModel",
  "androidX-lifecycle-liveData",
  "androidX-lifecycle-service"
]
androidX-room = [
  "androidX-room-runtime",
  "androidX-room-ktx"
]
appCenter = [
  "appCenter-analytics",
  "appCenter-crashes"
]
grpc = [
  "javax-annotation",
  "grpc-okhttp",
  "grpc-protobuf",
  "grpc-stub"
]
rikkax = [
  "rikkax-core",
  "rikkax-insets",
  "rikkax-material",
  "rikkax-borderview",
  "rikkax-appcompat",
  "rikkax-layoutinflater",
  "rikkax-recyclerview",
  "rikkax-simplemenu-preference"
]
zhaobozhen = [
  "zhaobozhen-me",
  "zhaobozhen-utils",
  "zhaobozhen-axml"
]
